spring:
  application:
    name: safeRealtor

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

file:
  upload-path: uploads/images

sms:
  enable: false

coolsms:
  api-key: ${COOLSMS_API_KEY}
  api-secret: ${COOLSMS_API_SECRET}
  from-number: ${COOLSMS_FROM_NUMBER}

agent:
  phone-number: ${AGENT_PHONE_NUMBER}

jwt:
  access-token-exp-time:  15  # Access Token 만료 시간 (분 단위)
  refresh-token-exp-time: 43200  # Refresh Token 만료 시간 (30일)
  secret: ${JWT_SECRET}

admin:
  userid: ${ADMIN_USERID}
  password: ${ADMIN_PASSWORD}
  phone-number: ${ADMIN_PHONE_NUMBER}